/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.go.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.go.FieldDecl;
import org.xtext.example.mydsl.go.GoPackage;
import org.xtext.example.mydsl.go.Type;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Field Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.impl.FieldDeclImpl#getIndentifierL <em>Indentifier L</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.impl.FieldDeclImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.impl.FieldDeclImpl#getEmbedded <em>Embedded</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.impl.FieldDeclImpl#getTag <em>Tag</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FieldDeclImpl extends MinimalEObjectImpl.Container implements FieldDecl
{
  /**
   * The default value of the '{@link #getIndentifierL() <em>Indentifier L</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIndentifierL()
   * @generated
   * @ordered
   */
  protected static final String INDENTIFIER_L_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIndentifierL() <em>Indentifier L</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIndentifierL()
   * @generated
   * @ordered
   */
  protected String indentifierL = INDENTIFIER_L_EDEFAULT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected Type type;

  /**
   * The default value of the '{@link #getEmbedded() <em>Embedded</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmbedded()
   * @generated
   * @ordered
   */
  protected static final String EMBEDDED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEmbedded() <em>Embedded</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmbedded()
   * @generated
   * @ordered
   */
  protected String embedded = EMBEDDED_EDEFAULT;

  /**
   * The default value of the '{@link #getTag() <em>Tag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTag()
   * @generated
   * @ordered
   */
  protected static final String TAG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTag() <em>Tag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTag()
   * @generated
   * @ordered
   */
  protected String tag = TAG_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FieldDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.FIELD_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIndentifierL()
  {
    return indentifierL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIndentifierL(String newIndentifierL)
  {
    String oldIndentifierL = indentifierL;
    indentifierL = newIndentifierL;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.FIELD_DECL__INDENTIFIER_L, oldIndentifierL, indentifierL));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(Type newType, NotificationChain msgs)
  {
    Type oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.FIELD_DECL__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(Type newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.FIELD_DECL__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.FIELD_DECL__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.FIELD_DECL__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEmbedded()
  {
    return embedded;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEmbedded(String newEmbedded)
  {
    String oldEmbedded = embedded;
    embedded = newEmbedded;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.FIELD_DECL__EMBEDDED, oldEmbedded, embedded));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTag()
  {
    return tag;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTag(String newTag)
  {
    String oldTag = tag;
    tag = newTag;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.FIELD_DECL__TAG, oldTag, tag));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoPackage.FIELD_DECL__TYPE:
        return basicSetType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.FIELD_DECL__INDENTIFIER_L:
        return getIndentifierL();
      case GoPackage.FIELD_DECL__TYPE:
        return getType();
      case GoPackage.FIELD_DECL__EMBEDDED:
        return getEmbedded();
      case GoPackage.FIELD_DECL__TAG:
        return getTag();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.FIELD_DECL__INDENTIFIER_L:
        setIndentifierL((String)newValue);
        return;
      case GoPackage.FIELD_DECL__TYPE:
        setType((Type)newValue);
        return;
      case GoPackage.FIELD_DECL__EMBEDDED:
        setEmbedded((String)newValue);
        return;
      case GoPackage.FIELD_DECL__TAG:
        setTag((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.FIELD_DECL__INDENTIFIER_L:
        setIndentifierL(INDENTIFIER_L_EDEFAULT);
        return;
      case GoPackage.FIELD_DECL__TYPE:
        setType((Type)null);
        return;
      case GoPackage.FIELD_DECL__EMBEDDED:
        setEmbedded(EMBEDDED_EDEFAULT);
        return;
      case GoPackage.FIELD_DECL__TAG:
        setTag(TAG_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.FIELD_DECL__INDENTIFIER_L:
        return INDENTIFIER_L_EDEFAULT == null ? indentifierL != null : !INDENTIFIER_L_EDEFAULT.equals(indentifierL);
      case GoPackage.FIELD_DECL__TYPE:
        return type != null;
      case GoPackage.FIELD_DECL__EMBEDDED:
        return EMBEDDED_EDEFAULT == null ? embedded != null : !EMBEDDED_EDEFAULT.equals(embedded);
      case GoPackage.FIELD_DECL__TAG:
        return TAG_EDEFAULT == null ? tag != null : !TAG_EDEFAULT.equals(tag);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (indentifierL: ");
    result.append(indentifierL);
    result.append(", embedded: ");
    result.append(embedded);
    result.append(", tag: ");
    result.append(tag);
    result.append(')');
    return result.toString();
  }

} //FieldDeclImpl
