/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.go.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.go.GoPackage;
import org.xtext.example.mydsl.go.ImportDecl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Import Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ImportDeclImpl extends MinimalEObjectImpl.Container implements ImportDecl
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImportDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.IMPORT_DECL;
  }

} //ImportDeclImpl
