/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.go.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.go.GoPackage;
import org.xtext.example.mydsl.go.ImportDecl;
import org.xtext.example.mydsl.go.ImportSpec;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Import Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.impl.ImportDeclImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.impl.ImportDeclImpl#getImports2 <em>Imports2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ImportDeclImpl extends MinimalEObjectImpl.Container implements ImportDecl
{
  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<ImportSpec> imports;

  /**
   * The cached value of the '{@link #getImports2() <em>Imports2</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports2()
   * @generated
   * @ordered
   */
  protected EList<ImportSpec> imports2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImportDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.IMPORT_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ImportSpec> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<ImportSpec>(ImportSpec.class, this, GoPackage.IMPORT_DECL__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ImportSpec> getImports2()
  {
    if (imports2 == null)
    {
      imports2 = new EObjectContainmentEList<ImportSpec>(ImportSpec.class, this, GoPackage.IMPORT_DECL__IMPORTS2);
    }
    return imports2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoPackage.IMPORT_DECL__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case GoPackage.IMPORT_DECL__IMPORTS2:
        return ((InternalEList<?>)getImports2()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.IMPORT_DECL__IMPORTS:
        return getImports();
      case GoPackage.IMPORT_DECL__IMPORTS2:
        return getImports2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.IMPORT_DECL__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends ImportSpec>)newValue);
        return;
      case GoPackage.IMPORT_DECL__IMPORTS2:
        getImports2().clear();
        getImports2().addAll((Collection<? extends ImportSpec>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.IMPORT_DECL__IMPORTS:
        getImports().clear();
        return;
      case GoPackage.IMPORT_DECL__IMPORTS2:
        getImports2().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.IMPORT_DECL__IMPORTS:
        return imports != null && !imports.isEmpty();
      case GoPackage.IMPORT_DECL__IMPORTS2:
        return imports2 != null && !imports2.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ImportDeclImpl
