/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.go.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.go.GoPackage;
import org.xtext.example.mydsl.go.MethodSpec;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Method Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MethodSpecImpl extends MinimalEObjectImpl.Container implements MethodSpec
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MethodSpecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.METHOD_SPEC;
  }

} //MethodSpecImpl
