/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.go.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.go.GoPackage;
import org.xtext.example.mydsl.go.PostStmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Post Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PostStmtImpl extends MinimalEObjectImpl.Container implements PostStmt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PostStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.POST_STMT;
  }

} //PostStmtImpl
