/**
 * generated by Xtext 2.14.0.RC1
 */
package org.xtext.example.mydsl.go.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.go.GoPackage;
import org.xtext.example.mydsl.go.RecvExpr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Recv Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RecvExprImpl extends MinimalEObjectImpl.Container implements RecvExpr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RecvExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.RECV_EXPR;
  }

} //RecvExprImpl
