/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.go.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.go.Expression;
import org.xtext.example.mydsl.go.GoPackage;
import org.xtext.example.mydsl.go.Slice;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Slice</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.impl.SliceImpl#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.impl.SliceImpl#getExpression2 <em>Expression2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.impl.SliceImpl#getExpression3 <em>Expression3</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.impl.SliceImpl#getExpression4 <em>Expression4</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.impl.SliceImpl#getExpression5 <em>Expression5</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SliceImpl extends MinimalEObjectImpl.Container implements Slice
{
  /**
   * The cached value of the '{@link #getExpression() <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression()
   * @generated
   * @ordered
   */
  protected Expression expression;

  /**
   * The cached value of the '{@link #getExpression2() <em>Expression2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression2()
   * @generated
   * @ordered
   */
  protected Expression expression2;

  /**
   * The cached value of the '{@link #getExpression3() <em>Expression3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression3()
   * @generated
   * @ordered
   */
  protected Expression expression3;

  /**
   * The cached value of the '{@link #getExpression4() <em>Expression4</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression4()
   * @generated
   * @ordered
   */
  protected Expression expression4;

  /**
   * The cached value of the '{@link #getExpression5() <em>Expression5</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression5()
   * @generated
   * @ordered
   */
  protected Expression expression5;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SliceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.SLICE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExpression()
  {
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression(Expression newExpression, NotificationChain msgs)
  {
    Expression oldExpression = expression;
    expression = newExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION, oldExpression, newExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpression(Expression newExpression)
  {
    if (newExpression != expression)
    {
      NotificationChain msgs = null;
      if (expression != null)
        msgs = ((InternalEObject)expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION, null, msgs);
      if (newExpression != null)
        msgs = ((InternalEObject)newExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION, null, msgs);
      msgs = basicSetExpression(newExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION, newExpression, newExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExpression2()
  {
    return expression2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression2(Expression newExpression2, NotificationChain msgs)
  {
    Expression oldExpression2 = expression2;
    expression2 = newExpression2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION2, oldExpression2, newExpression2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpression2(Expression newExpression2)
  {
    if (newExpression2 != expression2)
    {
      NotificationChain msgs = null;
      if (expression2 != null)
        msgs = ((InternalEObject)expression2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION2, null, msgs);
      if (newExpression2 != null)
        msgs = ((InternalEObject)newExpression2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION2, null, msgs);
      msgs = basicSetExpression2(newExpression2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION2, newExpression2, newExpression2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExpression3()
  {
    return expression3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression3(Expression newExpression3, NotificationChain msgs)
  {
    Expression oldExpression3 = expression3;
    expression3 = newExpression3;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION3, oldExpression3, newExpression3);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpression3(Expression newExpression3)
  {
    if (newExpression3 != expression3)
    {
      NotificationChain msgs = null;
      if (expression3 != null)
        msgs = ((InternalEObject)expression3).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION3, null, msgs);
      if (newExpression3 != null)
        msgs = ((InternalEObject)newExpression3).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION3, null, msgs);
      msgs = basicSetExpression3(newExpression3, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION3, newExpression3, newExpression3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExpression4()
  {
    return expression4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression4(Expression newExpression4, NotificationChain msgs)
  {
    Expression oldExpression4 = expression4;
    expression4 = newExpression4;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION4, oldExpression4, newExpression4);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpression4(Expression newExpression4)
  {
    if (newExpression4 != expression4)
    {
      NotificationChain msgs = null;
      if (expression4 != null)
        msgs = ((InternalEObject)expression4).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION4, null, msgs);
      if (newExpression4 != null)
        msgs = ((InternalEObject)newExpression4).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION4, null, msgs);
      msgs = basicSetExpression4(newExpression4, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION4, newExpression4, newExpression4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getExpression5()
  {
    return expression5;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression5(Expression newExpression5, NotificationChain msgs)
  {
    Expression oldExpression5 = expression5;
    expression5 = newExpression5;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION5, oldExpression5, newExpression5);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpression5(Expression newExpression5)
  {
    if (newExpression5 != expression5)
    {
      NotificationChain msgs = null;
      if (expression5 != null)
        msgs = ((InternalEObject)expression5).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION5, null, msgs);
      if (newExpression5 != null)
        msgs = ((InternalEObject)newExpression5).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.SLICE__EXPRESSION5, null, msgs);
      msgs = basicSetExpression5(newExpression5, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.SLICE__EXPRESSION5, newExpression5, newExpression5));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoPackage.SLICE__EXPRESSION:
        return basicSetExpression(null, msgs);
      case GoPackage.SLICE__EXPRESSION2:
        return basicSetExpression2(null, msgs);
      case GoPackage.SLICE__EXPRESSION3:
        return basicSetExpression3(null, msgs);
      case GoPackage.SLICE__EXPRESSION4:
        return basicSetExpression4(null, msgs);
      case GoPackage.SLICE__EXPRESSION5:
        return basicSetExpression5(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.SLICE__EXPRESSION:
        return getExpression();
      case GoPackage.SLICE__EXPRESSION2:
        return getExpression2();
      case GoPackage.SLICE__EXPRESSION3:
        return getExpression3();
      case GoPackage.SLICE__EXPRESSION4:
        return getExpression4();
      case GoPackage.SLICE__EXPRESSION5:
        return getExpression5();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.SLICE__EXPRESSION:
        setExpression((Expression)newValue);
        return;
      case GoPackage.SLICE__EXPRESSION2:
        setExpression2((Expression)newValue);
        return;
      case GoPackage.SLICE__EXPRESSION3:
        setExpression3((Expression)newValue);
        return;
      case GoPackage.SLICE__EXPRESSION4:
        setExpression4((Expression)newValue);
        return;
      case GoPackage.SLICE__EXPRESSION5:
        setExpression5((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.SLICE__EXPRESSION:
        setExpression((Expression)null);
        return;
      case GoPackage.SLICE__EXPRESSION2:
        setExpression2((Expression)null);
        return;
      case GoPackage.SLICE__EXPRESSION3:
        setExpression3((Expression)null);
        return;
      case GoPackage.SLICE__EXPRESSION4:
        setExpression4((Expression)null);
        return;
      case GoPackage.SLICE__EXPRESSION5:
        setExpression5((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.SLICE__EXPRESSION:
        return expression != null;
      case GoPackage.SLICE__EXPRESSION2:
        return expression2 != null;
      case GoPackage.SLICE__EXPRESSION3:
        return expression3 != null;
      case GoPackage.SLICE__EXPRESSION4:
        return expression4 != null;
      case GoPackage.SLICE__EXPRESSION5:
        return expression5 != null;
    }
    return super.eIsSet(featureID);
  }

} //SliceImpl
