/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.go.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.go.GoPackage;
import org.xtext.example.mydsl.go.TypeCaseClause;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Case Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TypeCaseClauseImpl extends MinimalEObjectImpl.Container implements TypeCaseClause
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeCaseClauseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.TYPE_CASE_CLAUSE;
  }

} //TypeCaseClauseImpl
