/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.go.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.go.GoPackage;
import org.xtext.example.mydsl.go.TypeSwitchGuard;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Switch Guard</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TypeSwitchGuardImpl extends MinimalEObjectImpl.Container implements TypeSwitchGuard
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeSwitchGuardImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.TYPE_SWITCH_GUARD;
  }

} //TypeSwitchGuardImpl
