/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alias Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getAliasDecl()
 * @model
 * @generated
 */
public interface AliasDecl extends TypeSpec
{
} // AliasDecl
