/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comm Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.CommCase#getStatementlist2 <em>Statementlist2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.CommCase#getSendstmt <em>Sendstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.CommCase#getRecvstmt <em>Recvstmt</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getCommCase()
 * @model
 * @generated
 */
public interface CommCase extends CommClause
{
  /**
   * Returns the value of the '<em><b>Statementlist2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statementlist2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statementlist2</em>' containment reference.
   * @see #setStatementlist2(StatementList)
   * @see org.xtext.example.mydsl.go.GoPackage#getCommCase_Statementlist2()
   * @model containment="true"
   * @generated
   */
  StatementList getStatementlist2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.CommCase#getStatementlist2 <em>Statementlist2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statementlist2</em>' containment reference.
   * @see #getStatementlist2()
   * @generated
   */
  void setStatementlist2(StatementList value);

  /**
   * Returns the value of the '<em><b>Sendstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sendstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sendstmt</em>' containment reference.
   * @see #setSendstmt(SendStmt)
   * @see org.xtext.example.mydsl.go.GoPackage#getCommCase_Sendstmt()
   * @model containment="true"
   * @generated
   */
  SendStmt getSendstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.CommCase#getSendstmt <em>Sendstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sendstmt</em>' containment reference.
   * @see #getSendstmt()
   * @generated
   */
  void setSendstmt(SendStmt value);

  /**
   * Returns the value of the '<em><b>Recvstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Recvstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recvstmt</em>' containment reference.
   * @see #setRecvstmt(RecvStmt)
   * @see org.xtext.example.mydsl.go.GoPackage#getCommCase_Recvstmt()
   * @model containment="true"
   * @generated
   */
  RecvStmt getRecvstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.CommCase#getRecvstmt <em>Recvstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Recvstmt</em>' containment reference.
   * @see #getRecvstmt()
   * @generated
   */
  void setRecvstmt(RecvStmt value);

} // CommCase
