/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.go;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Const Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.ConstDecl#getConstspec <em>Constspec</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.ConstDecl#getConstspec2 <em>Constspec2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getConstDecl()
 * @model
 * @generated
 */
public interface ConstDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Constspec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constspec</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constspec</em>' containment reference.
   * @see #setConstspec(ConstSpec)
   * @see org.xtext.example.mydsl.go.GoPackage#getConstDecl_Constspec()
   * @model containment="true"
   * @generated
   */
  ConstSpec getConstspec();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.ConstDecl#getConstspec <em>Constspec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constspec</em>' containment reference.
   * @see #getConstspec()
   * @generated
   */
  void setConstspec(ConstSpec value);

  /**
   * Returns the value of the '<em><b>Constspec2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.go.ConstSpec}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constspec2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constspec2</em>' containment reference list.
   * @see org.xtext.example.mydsl.go.GoPackage#getConstDecl_Constspec2()
   * @model containment="true"
   * @generated
   */
  EList<ConstSpec> getConstspec2();

} // ConstDecl
