/**
 * generated by Xtext 2.14.0.RC1
 */
package org.xtext.example.mydsl.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression List</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getExpressionList()
 * @model
 * @generated
 */
public interface ExpressionList extends RecvStmt
{
} // ExpressionList
