/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getExpressionStmt()
 * @model
 * @generated
 */
public interface ExpressionStmt extends SimpleStmt
{
} // ExpressionStmt
