/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.Expression2#getBop <em>Bop</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.Expression2#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.Expression2#getExpression2 <em>Expression2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getExpression2()
 * @model
 * @generated
 */
public interface Expression2 extends EObject
{
  /**
   * Returns the value of the '<em><b>Bop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bop</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bop</em>' attribute.
   * @see #setBop(String)
   * @see org.xtext.example.mydsl.go.GoPackage#getExpression2_Bop()
   * @model
   * @generated
   */
  String getBop();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.Expression2#getBop <em>Bop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bop</em>' attribute.
   * @see #getBop()
   * @generated
   */
  void setBop(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see org.xtext.example.mydsl.go.GoPackage#getExpression2_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.Expression2#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Expression2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression2</em>' containment reference.
   * @see #setExpression2(Expression2)
   * @see org.xtext.example.mydsl.go.GoPackage#getExpression2_Expression2()
   * @model containment="true"
   * @generated
   */
  Expression2 getExpression2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.Expression2#getExpression2 <em>Expression2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression2</em>' containment reference.
   * @see #getExpression2()
   * @generated
   */
  void setExpression2(Expression2 value);

} // Expression2
