/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Case Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.ExprCaseClause#getExpr <em>Expr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.ExprCaseClause#getStatementlist <em>Statementlist</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getExprCaseClause()
 * @model
 * @generated
 */
public interface ExprCaseClause extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(ExprSwitchCase)
   * @see org.xtext.example.mydsl.go.GoPackage#getExprCaseClause_Expr()
   * @model containment="true"
   * @generated
   */
  ExprSwitchCase getExpr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.ExprCaseClause#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(ExprSwitchCase value);

  /**
   * Returns the value of the '<em><b>Statementlist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statementlist</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statementlist</em>' containment reference.
   * @see #setStatementlist(StatementList)
   * @see org.xtext.example.mydsl.go.GoPackage#getExprCaseClause_Statementlist()
   * @model containment="true"
   * @generated
   */
  StatementList getStatementlist();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.ExprCaseClause#getStatementlist <em>Statementlist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statementlist</em>' containment reference.
   * @see #getStatementlist()
   * @generated
   */
  void setStatementlist(StatementList value);

} // ExprCaseClause
