/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.FieldDecl#getIndentifierL <em>Indentifier L</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.FieldDecl#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getFieldDecl()
 * @model
 * @generated
 */
public interface FieldDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Indentifier L</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Indentifier L</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indentifier L</em>' attribute.
   * @see #setIndentifierL(String)
   * @see org.xtext.example.mydsl.go.GoPackage#getFieldDecl_IndentifierL()
   * @model
   * @generated
   */
  String getIndentifierL();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.FieldDecl#getIndentifierL <em>Indentifier L</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Indentifier L</em>' attribute.
   * @see #getIndentifierL()
   * @generated
   */
  void setIndentifierL(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see org.xtext.example.mydsl.go.GoPackage#getFieldDecl_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.FieldDecl#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

} // FieldDecl
