/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getMethodExpr()
 * @model
 * @generated
 */
public interface MethodExpr extends PrimaryExpr
{
} // MethodExpr
