/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.PackageClause#getPack <em>Pack</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getPackageClause()
 * @model
 * @generated
 */
public interface PackageClause extends EObject
{
  /**
   * Returns the value of the '<em><b>Pack</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pack</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pack</em>' attribute.
   * @see #setPack(String)
   * @see org.xtext.example.mydsl.go.GoPackage#getPackageClause_Pack()
   * @model
   * @generated
   */
  String getPack();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.PackageClause#getPack <em>Pack</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pack</em>' attribute.
   * @see #getPack()
   * @generated
   */
  void setPack(String value);

} // PackageClause
