/**
 * generated by Xtext 2.14.0.RC1
 */
package org.xtext.example.mydsl.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Expr2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.PrimaryExpr2#getSelector <em>Selector</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.PrimaryExpr2#getPr <em>Pr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.PrimaryExpr2#getIndex <em>Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.PrimaryExpr2#getSlice <em>Slice</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.PrimaryExpr2#getTypeass <em>Typeass</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.PrimaryExpr2#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getPrimaryExpr2()
 * @model
 * @generated
 */
public interface PrimaryExpr2 extends EObject
{
  /**
   * Returns the value of the '<em><b>Selector</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Selector</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' attribute.
   * @see #setSelector(String)
   * @see org.xtext.example.mydsl.go.GoPackage#getPrimaryExpr2_Selector()
   * @model
   * @generated
   */
  String getSelector();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.PrimaryExpr2#getSelector <em>Selector</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selector</em>' attribute.
   * @see #getSelector()
   * @generated
   */
  void setSelector(String value);

  /**
   * Returns the value of the '<em><b>Pr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pr</em>' containment reference.
   * @see #setPr(PrimaryExpr2)
   * @see org.xtext.example.mydsl.go.GoPackage#getPrimaryExpr2_Pr()
   * @model containment="true"
   * @generated
   */
  PrimaryExpr2 getPr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.PrimaryExpr2#getPr <em>Pr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pr</em>' containment reference.
   * @see #getPr()
   * @generated
   */
  void setPr(PrimaryExpr2 value);

  /**
   * Returns the value of the '<em><b>Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Index</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' containment reference.
   * @see #setIndex(Index)
   * @see org.xtext.example.mydsl.go.GoPackage#getPrimaryExpr2_Index()
   * @model containment="true"
   * @generated
   */
  Index getIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.PrimaryExpr2#getIndex <em>Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' containment reference.
   * @see #getIndex()
   * @generated
   */
  void setIndex(Index value);

  /**
   * Returns the value of the '<em><b>Slice</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Slice</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slice</em>' containment reference.
   * @see #setSlice(Slice)
   * @see org.xtext.example.mydsl.go.GoPackage#getPrimaryExpr2_Slice()
   * @model containment="true"
   * @generated
   */
  Slice getSlice();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.PrimaryExpr2#getSlice <em>Slice</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Slice</em>' containment reference.
   * @see #getSlice()
   * @generated
   */
  void setSlice(Slice value);

  /**
   * Returns the value of the '<em><b>Typeass</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typeass</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typeass</em>' containment reference.
   * @see #setTypeass(TypeAssertion)
   * @see org.xtext.example.mydsl.go.GoPackage#getPrimaryExpr2_Typeass()
   * @model containment="true"
   * @generated
   */
  TypeAssertion getTypeass();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.PrimaryExpr2#getTypeass <em>Typeass</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typeass</em>' containment reference.
   * @see #getTypeass()
   * @generated
   */
  void setTypeass(TypeAssertion value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arguments</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference.
   * @see #setArguments(Arguments)
   * @see org.xtext.example.mydsl.go.GoPackage#getPrimaryExpr2_Arguments()
   * @model containment="true"
   * @generated
   */
  Arguments getArguments();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.PrimaryExpr2#getArguments <em>Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arguments</em>' containment reference.
   * @see #getArguments()
   * @generated
   */
  void setArguments(Arguments value);

} // PrimaryExpr2
