/**
 * generated by Xtext 2.14.0.RC1
 */
package org.xtext.example.mydsl.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Short Var Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.ShortVarDecl#getIdl <em>Idl</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.ShortVarDecl#getEpl <em>Epl</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getShortVarDecl()
 * @model
 * @generated
 */
public interface ShortVarDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Idl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Idl</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Idl</em>' attribute.
   * @see #setIdl(String)
   * @see org.xtext.example.mydsl.go.GoPackage#getShortVarDecl_Idl()
   * @model
   * @generated
   */
  String getIdl();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.ShortVarDecl#getIdl <em>Idl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Idl</em>' attribute.
   * @see #getIdl()
   * @generated
   */
  void setIdl(String value);

  /**
   * Returns the value of the '<em><b>Epl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Epl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Epl</em>' containment reference.
   * @see #setEpl(ExpressionList)
   * @see org.xtext.example.mydsl.go.GoPackage#getShortVarDecl_Epl()
   * @model containment="true"
   * @generated
   */
  ExpressionList getEpl();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.ShortVarDecl#getEpl <em>Epl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Epl</em>' containment reference.
   * @see #getEpl()
   * @generated
   */
  void setEpl(ExpressionList value);

} // ShortVarDecl
