/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Signature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.Signature#getFunctionbody <em>Functionbody</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getSignature()
 * @model
 * @generated
 */
public interface Signature extends FunctionType, FunctionLit
{
  /**
   * Returns the value of the '<em><b>Functionbody</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Functionbody</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functionbody</em>' containment reference.
   * @see #setFunctionbody(FunctionBody)
   * @see org.xtext.example.mydsl.go.GoPackage#getSignature_Functionbody()
   * @model containment="true"
   * @generated
   */
  FunctionBody getFunctionbody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.Signature#getFunctionbody <em>Functionbody</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Functionbody</em>' containment reference.
   * @see #getFunctionbody()
   * @generated
   */
  void setFunctionbody(FunctionBody value);

} // Signature
