/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.Type#getTp <em>Tp</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.Type#getTp2 <em>Tp2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.Type#getTp3 <em>Tp3</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getType()
 * @model
 * @generated
 */
public interface Type extends ElementType, BaseType, KeyType, TypeAssertion
{
  /**
   * Returns the value of the '<em><b>Tp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tp</em>' containment reference.
   * @see #setTp(TypeName)
   * @see org.xtext.example.mydsl.go.GoPackage#getType_Tp()
   * @model containment="true"
   * @generated
   */
  TypeName getTp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.Type#getTp <em>Tp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tp</em>' containment reference.
   * @see #getTp()
   * @generated
   */
  void setTp(TypeName value);

  /**
   * Returns the value of the '<em><b>Tp2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tp2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tp2</em>' containment reference.
   * @see #setTp2(TypeLit)
   * @see org.xtext.example.mydsl.go.GoPackage#getType_Tp2()
   * @model containment="true"
   * @generated
   */
  TypeLit getTp2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.Type#getTp2 <em>Tp2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tp2</em>' containment reference.
   * @see #getTp2()
   * @generated
   */
  void setTp2(TypeLit value);

  /**
   * Returns the value of the '<em><b>Tp3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tp3</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tp3</em>' containment reference.
   * @see #setTp3(Type)
   * @see org.xtext.example.mydsl.go.GoPackage#getType_Tp3()
   * @model containment="true"
   * @generated
   */
  Type getTp3();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.Type#getTp3 <em>Tp3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tp3</em>' containment reference.
   * @see #getTp3()
   * @generated
   */
  void setTp3(Type value);

} // Type
