/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Def</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getTypeDef()
 * @model
 * @generated
 */
public interface TypeDef extends TypeSpec
{
} // TypeDef
