/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.go;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Switch Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.TypeSwitchStmt#getSimplestm <em>Simplestm</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.TypeSwitchStmt#getTypesg <em>Typesg</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.TypeSwitchStmt#getTypecc <em>Typecc</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getTypeSwitchStmt()
 * @model
 * @generated
 */
public interface TypeSwitchStmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Simplestm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simplestm</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simplestm</em>' containment reference.
   * @see #setSimplestm(SimpleStmt)
   * @see org.xtext.example.mydsl.go.GoPackage#getTypeSwitchStmt_Simplestm()
   * @model containment="true"
   * @generated
   */
  SimpleStmt getSimplestm();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.TypeSwitchStmt#getSimplestm <em>Simplestm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simplestm</em>' containment reference.
   * @see #getSimplestm()
   * @generated
   */
  void setSimplestm(SimpleStmt value);

  /**
   * Returns the value of the '<em><b>Typesg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typesg</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typesg</em>' containment reference.
   * @see #setTypesg(TypeSwitchGuard)
   * @see org.xtext.example.mydsl.go.GoPackage#getTypeSwitchStmt_Typesg()
   * @model containment="true"
   * @generated
   */
  TypeSwitchGuard getTypesg();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.TypeSwitchStmt#getTypesg <em>Typesg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typesg</em>' containment reference.
   * @see #getTypesg()
   * @generated
   */
  void setTypesg(TypeSwitchGuard value);

  /**
   * Returns the value of the '<em><b>Typecc</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.go.TypeCaseClause}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typecc</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typecc</em>' containment reference list.
   * @see org.xtext.example.mydsl.go.GoPackage#getTypeSwitchStmt_Typecc()
   * @model containment="true"
   * @generated
   */
  EList<TypeCaseClause> getTypecc();

} // TypeSwitchStmt
