/**
 * generated by Xtext 2.14.0.RC1
 */
package org.xtext.example.mydsl.go;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.go.VarDecl#getVarspec <em>Varspec</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.go.VarDecl#getVarspec2 <em>Varspec2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.go.GoPackage#getVarDecl()
 * @model
 * @generated
 */
public interface VarDecl extends Declaration
{
  /**
   * Returns the value of the '<em><b>Varspec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Varspec</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Varspec</em>' containment reference.
   * @see #setVarspec(VarSpec)
   * @see org.xtext.example.mydsl.go.GoPackage#getVarDecl_Varspec()
   * @model containment="true"
   * @generated
   */
  VarSpec getVarspec();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.go.VarDecl#getVarspec <em>Varspec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Varspec</em>' containment reference.
   * @see #getVarspec()
   * @generated
   */
  void setVarspec(VarSpec value);

  /**
   * Returns the value of the '<em><b>Varspec2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.go.VarSpec}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Varspec2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Varspec2</em>' containment reference list.
   * @see org.xtext.example.mydsl.go.GoPackage#getVarDecl_Varspec2()
   * @model containment="true"
   * @generated
   */
  EList<VarSpec> getVarspec2();

} // VarDecl
